import { Inter } from "next/font/google";
import "../styles/globals.scss";
import Navbar from "@/Components/Navbar/Navbar";
import { Analytics } from "@vercel/analytics/react";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Esmeralda's Salty Air Retreat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
